# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladderlevelexercise',
            name='ladder',
        ),
        migrations.AddField(
            model_name='ladderlevel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ladderlevel',
            name='fear_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='ladderlevel',
            name='situation',
            field=models.TextField(max_length=99999),
        ),
        migrations.DeleteModel(
            name='ladderLevelExercise',
        ),
    ]
