# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ladder', '0002_auto_20180310_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ladderExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('situation', models.TextField(max_length=99999)),
                ('fear_rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('completed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ladderlevel',
            name='patient',
        ),
        migrations.DeleteModel(
            name='ladderLevel',
        ),
    ]
